# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_auto_20161127_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
